//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consentRetrieverq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consentRetrieverq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:EmployeeWS/types}hrmSsystem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hrsPersonId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consentRetrieverq", propOrder = {
    "hrsPersonId"
})
public class ConsentRetrieverq
    extends HrmSsystem
{

    protected int hrsPersonId;

    /**
     * Gets the value of the hrsPersonId property.
     * 
     */
    public int getHrsPersonId() {
        return hrsPersonId;
    }

    /**
     * Sets the value of the hrsPersonId property.
     * 
     */
    public void setHrsPersonId(int value) {
        this.hrsPersonId = value;
    }

}
