//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getEmpName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getEmpName"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetEmpNameRq_1" type="{urn:EmployeeWS/types}getEmpNameRq" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmpName", propOrder = {
    "getEmpNameRq1"
})
public class GetEmpName {

    @XmlElement(name = "GetEmpNameRq_1")
    protected GetEmpNameRq getEmpNameRq1;

    /**
     * Gets the value of the getEmpNameRq1 property.
     * 
     * @return
     *     possible object is
     *     {@link GetEmpNameRq }
     *     
     */
    public GetEmpNameRq getGetEmpNameRq1() {
        return getEmpNameRq1;
    }

    /**
     * Sets the value of the getEmpNameRq1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetEmpNameRq }
     *     
     */
    public void setGetEmpNameRq1(GetEmpNameRq value) {
        this.getEmpNameRq1 = value;
    }

}
