//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getLicenseRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getLicenseRs"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accomType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bossFirst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bossLast" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bossRC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bossTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emplid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emplidTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="evm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="expireDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstEng" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="headerRs" type="{urn:EmployeeWS/types}headerRs" minOccurs="0"/&gt;
 *         &lt;element name="lastEng" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="leaveStat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="licNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nationalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phoneEx" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rccode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseDescr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="titleEng" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLicenseRs", propOrder = {
    "accomType",
    "bossFirst",
    "bossLast",
    "bossRC",
    "bossTitle",
    "email",
    "emplid",
    "emplidTo",
    "evm",
    "expireDate",
    "fax",
    "firstEng",
    "firstName",
    "headerRs",
    "lastEng",
    "lastName",
    "leaveStat",
    "licNumber",
    "mobile",
    "nationalId",
    "phone",
    "phoneEx",
    "rccode",
    "responseCode",
    "responseDescr",
    "title",
    "titleEng"
})
public class GetLicenseRs {

    protected String accomType;
    protected String bossFirst;
    protected String bossLast;
    protected String bossRC;
    protected String bossTitle;
    protected String email;
    protected String emplid;
    protected String emplidTo;
    protected String evm;
    protected String expireDate;
    protected String fax;
    protected String firstEng;
    protected String firstName;
    protected HeaderRs headerRs;
    protected String lastEng;
    protected String lastName;
    protected String leaveStat;
    protected String licNumber;
    protected String mobile;
    protected String nationalId;
    protected String phone;
    protected String phoneEx;
    protected String rccode;
    protected String responseCode;
    protected String responseDescr;
    protected String title;
    protected String titleEng;

    /**
     * Gets the value of the accomType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccomType() {
        return accomType;
    }

    /**
     * Sets the value of the accomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccomType(String value) {
        this.accomType = value;
    }

    /**
     * Gets the value of the bossFirst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBossFirst() {
        return bossFirst;
    }

    /**
     * Sets the value of the bossFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBossFirst(String value) {
        this.bossFirst = value;
    }

    /**
     * Gets the value of the bossLast property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBossLast() {
        return bossLast;
    }

    /**
     * Sets the value of the bossLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBossLast(String value) {
        this.bossLast = value;
    }

    /**
     * Gets the value of the bossRC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBossRC() {
        return bossRC;
    }

    /**
     * Sets the value of the bossRC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBossRC(String value) {
        this.bossRC = value;
    }

    /**
     * Gets the value of the bossTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBossTitle() {
        return bossTitle;
    }

    /**
     * Sets the value of the bossTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBossTitle(String value) {
        this.bossTitle = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the emplid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplid() {
        return emplid;
    }

    /**
     * Sets the value of the emplid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplid(String value) {
        this.emplid = value;
    }

    /**
     * Gets the value of the emplidTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplidTo() {
        return emplidTo;
    }

    /**
     * Sets the value of the emplidTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplidTo(String value) {
        this.emplidTo = value;
    }

    /**
     * Gets the value of the evm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvm() {
        return evm;
    }

    /**
     * Sets the value of the evm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvm(String value) {
        this.evm = value;
    }

    /**
     * Gets the value of the expireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * Sets the value of the expireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireDate(String value) {
        this.expireDate = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the firstEng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstEng() {
        return firstEng;
    }

    /**
     * Sets the value of the firstEng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstEng(String value) {
        this.firstEng = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the headerRs property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderRs }
     *     
     */
    public HeaderRs getHeaderRs() {
        return headerRs;
    }

    /**
     * Sets the value of the headerRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderRs }
     *     
     */
    public void setHeaderRs(HeaderRs value) {
        this.headerRs = value;
    }

    /**
     * Gets the value of the lastEng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastEng() {
        return lastEng;
    }

    /**
     * Sets the value of the lastEng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastEng(String value) {
        this.lastEng = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the leaveStat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaveStat() {
        return leaveStat;
    }

    /**
     * Sets the value of the leaveStat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaveStat(String value) {
        this.leaveStat = value;
    }

    /**
     * Gets the value of the licNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicNumber() {
        return licNumber;
    }

    /**
     * Sets the value of the licNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicNumber(String value) {
        this.licNumber = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the nationalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalId() {
        return nationalId;
    }

    /**
     * Sets the value of the nationalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalId(String value) {
        this.nationalId = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the phoneEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneEx() {
        return phoneEx;
    }

    /**
     * Sets the value of the phoneEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneEx(String value) {
        this.phoneEx = value;
    }

    /**
     * Gets the value of the rccode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRccode() {
        return rccode;
    }

    /**
     * Sets the value of the rccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRccode(String value) {
        this.rccode = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the responseDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDescr() {
        return responseDescr;
    }

    /**
     * Sets the value of the responseDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDescr(String value) {
        this.responseDescr = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the titleEng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleEng() {
        return titleEng;
    }

    /**
     * Sets the value of the titleEng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleEng(String value) {
        this.titleEng = value;
    }

}
