//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hrmSsystem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hrmSsystem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="systemName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hrmSsystem", propOrder = {
    "systemName"
})
@XmlSeeAlso({
    KtbGetEmpByEmailRequestList.class,
    KtbGetEmpByEmailList.class,
    HeaderRq.class,
    KtbReqLicSub.class,
    GetLicenseRq.class,
    KtbEmpBussinessCardRq.class,
    KtbEmployeeWS2 .class,
    ConsentInsertrq.class,
    KtbGetConsentFlagList.class,
    KtbGetConsentList.class,
    KtbGetConsentMsgList.class,
    ConsentRetrieveFlagRq.class,
    KtbEmployeeWS.class,
    EmployeeReq.class,
    KtbEmpAbsRq.class,
    KtbGetPolicyRequestList.class,
    KtbGetPolicyList.class,
    KtbEmployeeByRankOrCostCenterRq.class,
    KtbLicenseInfoRq.class,
    GetEmpNameRq.class,
    KtbEmpPhotoRq.class,
    KtbReqLic.class,
    GetEmpRCRq.class,
    KtbEmpSignDetailRq.class,
    ConsentRetrieverq.class,
    KtbEmpContactRq.class,
    KtbEmpPhotoListRq.class
})
public abstract class HrmSsystem {

    protected String systemName;

    /**
     * Gets the value of the systemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * Sets the value of the systemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemName(String value) {
        this.systemName = value;
    }

}
