//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ktbEmpBussinessCardList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ktbEmpBussinessCardList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="address1_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address1_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address2_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address2_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="costCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="costCenterDescr_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="costCenterDescr_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="district_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="district_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emplRecordNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="emplid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fax_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fax_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="locationName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="locationName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mobilePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phone_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phone_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postal_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postal_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="provinceName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="provinceName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rankCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rankName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rankName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tambon_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tambon_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="title_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="title_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ktbEmpBussinessCardList", propOrder = {
    "address1En",
    "address1Th",
    "address2En",
    "address2Th",
    "costCenter",
    "costCenterDescrEn",
    "costCenterDescrTh",
    "districtEn",
    "districtTh",
    "email",
    "emplRecordNo",
    "emplid",
    "faxEn",
    "faxTh",
    "firstNameEn",
    "firstNameTh",
    "lastNameEn",
    "lastNameTh",
    "location",
    "locationNameEn",
    "locationNameTh",
    "mobilePhone",
    "phoneEn",
    "phoneTh",
    "postalEn",
    "postalTh",
    "provinceNameEn",
    "provinceNameTh",
    "rankCode",
    "rankNameEn",
    "rankNameTh",
    "tambonEn",
    "tambonTh",
    "titleEn",
    "titleTh"
})
public class KtbEmpBussinessCardList {

    @XmlElement(name = "address1_en")
    protected String address1En;
    @XmlElement(name = "address1_th")
    protected String address1Th;
    @XmlElement(name = "address2_en")
    protected String address2En;
    @XmlElement(name = "address2_th")
    protected String address2Th;
    protected String costCenter;
    @XmlElement(name = "costCenterDescr_en")
    protected String costCenterDescrEn;
    @XmlElement(name = "costCenterDescr_th")
    protected String costCenterDescrTh;
    @XmlElement(name = "district_en")
    protected String districtEn;
    @XmlElement(name = "district_th")
    protected String districtTh;
    protected String email;
    protected String emplRecordNo;
    protected String emplid;
    @XmlElement(name = "fax_en")
    protected String faxEn;
    @XmlElement(name = "fax_th")
    protected String faxTh;
    @XmlElement(name = "firstName_en")
    protected String firstNameEn;
    @XmlElement(name = "firstName_th")
    protected String firstNameTh;
    @XmlElement(name = "lastName_en")
    protected String lastNameEn;
    @XmlElement(name = "lastName_th")
    protected String lastNameTh;
    protected String location;
    @XmlElement(name = "locationName_en")
    protected String locationNameEn;
    @XmlElement(name = "locationName_th")
    protected String locationNameTh;
    protected String mobilePhone;
    @XmlElement(name = "phone_en")
    protected String phoneEn;
    @XmlElement(name = "phone_th")
    protected String phoneTh;
    @XmlElement(name = "postal_en")
    protected String postalEn;
    @XmlElement(name = "postal_th")
    protected String postalTh;
    @XmlElement(name = "provinceName_en")
    protected String provinceNameEn;
    @XmlElement(name = "provinceName_th")
    protected String provinceNameTh;
    protected String rankCode;
    @XmlElement(name = "rankName_en")
    protected String rankNameEn;
    @XmlElement(name = "rankName_th")
    protected String rankNameTh;
    @XmlElement(name = "tambon_en")
    protected String tambonEn;
    @XmlElement(name = "tambon_th")
    protected String tambonTh;
    @XmlElement(name = "title_en")
    protected String titleEn;
    @XmlElement(name = "title_th")
    protected String titleTh;

    /**
     * Gets the value of the address1En property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1En() {
        return address1En;
    }

    /**
     * Sets the value of the address1En property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1En(String value) {
        this.address1En = value;
    }

    /**
     * Gets the value of the address1Th property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1Th() {
        return address1Th;
    }

    /**
     * Sets the value of the address1Th property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1Th(String value) {
        this.address1Th = value;
    }

    /**
     * Gets the value of the address2En property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2En() {
        return address2En;
    }

    /**
     * Sets the value of the address2En property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2En(String value) {
        this.address2En = value;
    }

    /**
     * Gets the value of the address2Th property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2Th() {
        return address2Th;
    }

    /**
     * Sets the value of the address2Th property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2Th(String value) {
        this.address2Th = value;
    }

    /**
     * Gets the value of the costCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenter() {
        return costCenter;
    }

    /**
     * Sets the value of the costCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenter(String value) {
        this.costCenter = value;
    }

    /**
     * Gets the value of the costCenterDescrEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterDescrEn() {
        return costCenterDescrEn;
    }

    /**
     * Sets the value of the costCenterDescrEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterDescrEn(String value) {
        this.costCenterDescrEn = value;
    }

    /**
     * Gets the value of the costCenterDescrTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterDescrTh() {
        return costCenterDescrTh;
    }

    /**
     * Sets the value of the costCenterDescrTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterDescrTh(String value) {
        this.costCenterDescrTh = value;
    }

    /**
     * Gets the value of the districtEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictEn() {
        return districtEn;
    }

    /**
     * Sets the value of the districtEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictEn(String value) {
        this.districtEn = value;
    }

    /**
     * Gets the value of the districtTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrictTh() {
        return districtTh;
    }

    /**
     * Sets the value of the districtTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrictTh(String value) {
        this.districtTh = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the emplRecordNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplRecordNo() {
        return emplRecordNo;
    }

    /**
     * Sets the value of the emplRecordNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplRecordNo(String value) {
        this.emplRecordNo = value;
    }

    /**
     * Gets the value of the emplid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmplid() {
        return emplid;
    }

    /**
     * Sets the value of the emplid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmplid(String value) {
        this.emplid = value;
    }

    /**
     * Gets the value of the faxEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxEn() {
        return faxEn;
    }

    /**
     * Sets the value of the faxEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxEn(String value) {
        this.faxEn = value;
    }

    /**
     * Gets the value of the faxTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxTh() {
        return faxTh;
    }

    /**
     * Sets the value of the faxTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxTh(String value) {
        this.faxTh = value;
    }

    /**
     * Gets the value of the firstNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstNameEn() {
        return firstNameEn;
    }

    /**
     * Sets the value of the firstNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstNameEn(String value) {
        this.firstNameEn = value;
    }

    /**
     * Gets the value of the firstNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstNameTh() {
        return firstNameTh;
    }

    /**
     * Sets the value of the firstNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstNameTh(String value) {
        this.firstNameTh = value;
    }

    /**
     * Gets the value of the lastNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastNameEn() {
        return lastNameEn;
    }

    /**
     * Sets the value of the lastNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastNameEn(String value) {
        this.lastNameEn = value;
    }

    /**
     * Gets the value of the lastNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastNameTh() {
        return lastNameTh;
    }

    /**
     * Sets the value of the lastNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastNameTh(String value) {
        this.lastNameTh = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the locationNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationNameEn() {
        return locationNameEn;
    }

    /**
     * Sets the value of the locationNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationNameEn(String value) {
        this.locationNameEn = value;
    }

    /**
     * Gets the value of the locationNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationNameTh() {
        return locationNameTh;
    }

    /**
     * Sets the value of the locationNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationNameTh(String value) {
        this.locationNameTh = value;
    }

    /**
     * Gets the value of the mobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * Sets the value of the mobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhone(String value) {
        this.mobilePhone = value;
    }

    /**
     * Gets the value of the phoneEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneEn() {
        return phoneEn;
    }

    /**
     * Sets the value of the phoneEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneEn(String value) {
        this.phoneEn = value;
    }

    /**
     * Gets the value of the phoneTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneTh() {
        return phoneTh;
    }

    /**
     * Sets the value of the phoneTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneTh(String value) {
        this.phoneTh = value;
    }

    /**
     * Gets the value of the postalEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalEn() {
        return postalEn;
    }

    /**
     * Sets the value of the postalEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalEn(String value) {
        this.postalEn = value;
    }

    /**
     * Gets the value of the postalTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalTh() {
        return postalTh;
    }

    /**
     * Sets the value of the postalTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalTh(String value) {
        this.postalTh = value;
    }

    /**
     * Gets the value of the provinceNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceNameEn() {
        return provinceNameEn;
    }

    /**
     * Sets the value of the provinceNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceNameEn(String value) {
        this.provinceNameEn = value;
    }

    /**
     * Gets the value of the provinceNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceNameTh() {
        return provinceNameTh;
    }

    /**
     * Sets the value of the provinceNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceNameTh(String value) {
        this.provinceNameTh = value;
    }

    /**
     * Gets the value of the rankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRankCode() {
        return rankCode;
    }

    /**
     * Sets the value of the rankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRankCode(String value) {
        this.rankCode = value;
    }

    /**
     * Gets the value of the rankNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRankNameEn() {
        return rankNameEn;
    }

    /**
     * Sets the value of the rankNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRankNameEn(String value) {
        this.rankNameEn = value;
    }

    /**
     * Gets the value of the rankNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRankNameTh() {
        return rankNameTh;
    }

    /**
     * Sets the value of the rankNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRankNameTh(String value) {
        this.rankNameTh = value;
    }

    /**
     * Gets the value of the tambonEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTambonEn() {
        return tambonEn;
    }

    /**
     * Sets the value of the tambonEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTambonEn(String value) {
        this.tambonEn = value;
    }

    /**
     * Gets the value of the tambonTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTambonTh() {
        return tambonTh;
    }

    /**
     * Sets the value of the tambonTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTambonTh(String value) {
        this.tambonTh = value;
    }

    /**
     * Gets the value of the titleEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleEn() {
        return titleEn;
    }

    /**
     * Sets the value of the titleEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleEn(String value) {
        this.titleEn = value;
    }

    /**
     * Gets the value of the titleTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleTh() {
        return titleTh;
    }

    /**
     * Sets the value of the titleTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleTh(String value) {
        this.titleTh = value;
    }

}
