//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ktbEmpBussinessCardRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ktbEmpBussinessCardRes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="headerRs" type="{urn:EmployeeWS/types}headerRs" minOccurs="0"/&gt;
 *         &lt;element name="itemList" type="{urn:EmployeeWS/types}ktbEmpBussinessCardList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="responseAddress1_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseAddress1_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseAddress2_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseAddress2_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseCostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseCostCenterDescr_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseCostCenterDescr_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseDescr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseDistrict_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseDistrict_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseEmplRecordNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseEmplid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseFax_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseFax_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseFirstName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseFirstName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseLastName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseLastName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseLocationName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseLocationName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseMobilePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responsePhone_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responsePhone_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responsePostal_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responsePostal_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseProvinceName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseProvinceName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseRankCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseRankName_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseRankName_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseTambon_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseTambon_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseTitle_en" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="responseTitle_th" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ktbEmpBussinessCardRes", propOrder = {
    "headerRs",
    "itemList",
    "responseAddress1En",
    "responseAddress1Th",
    "responseAddress2En",
    "responseAddress2Th",
    "responseCode",
    "responseCostCenter",
    "responseCostCenterDescrEn",
    "responseCostCenterDescrTh",
    "responseDescr",
    "responseDistrictEn",
    "responseDistrictTh",
    "responseEmail",
    "responseEmplRecordNo",
    "responseEmplid",
    "responseFaxEn",
    "responseFaxTh",
    "responseFirstNameEn",
    "responseFirstNameTh",
    "responseLastNameEn",
    "responseLastNameTh",
    "responseLocation",
    "responseLocationNameEn",
    "responseLocationNameTh",
    "responseMobilePhone",
    "responsePhoneEn",
    "responsePhoneTh",
    "responsePostalEn",
    "responsePostalTh",
    "responseProvinceNameEn",
    "responseProvinceNameTh",
    "responseRankCode",
    "responseRankNameEn",
    "responseRankNameTh",
    "responseTambonEn",
    "responseTambonTh",
    "responseTitleEn",
    "responseTitleTh"
})
public class KtbEmpBussinessCardRes {

    protected HeaderRs headerRs;
    @XmlElement(nillable = true)
    protected List<KtbEmpBussinessCardList> itemList;
    @XmlElement(name = "responseAddress1_en")
    protected String responseAddress1En;
    @XmlElement(name = "responseAddress1_th")
    protected String responseAddress1Th;
    @XmlElement(name = "responseAddress2_en")
    protected String responseAddress2En;
    @XmlElement(name = "responseAddress2_th")
    protected String responseAddress2Th;
    protected String responseCode;
    protected String responseCostCenter;
    @XmlElement(name = "responseCostCenterDescr_en")
    protected String responseCostCenterDescrEn;
    @XmlElement(name = "responseCostCenterDescr_th")
    protected String responseCostCenterDescrTh;
    protected String responseDescr;
    @XmlElement(name = "responseDistrict_en")
    protected String responseDistrictEn;
    @XmlElement(name = "responseDistrict_th")
    protected String responseDistrictTh;
    protected String responseEmail;
    protected String responseEmplRecordNo;
    protected String responseEmplid;
    @XmlElement(name = "responseFax_en")
    protected String responseFaxEn;
    @XmlElement(name = "responseFax_th")
    protected String responseFaxTh;
    @XmlElement(name = "responseFirstName_en")
    protected String responseFirstNameEn;
    @XmlElement(name = "responseFirstName_th")
    protected String responseFirstNameTh;
    @XmlElement(name = "responseLastName_en")
    protected String responseLastNameEn;
    @XmlElement(name = "responseLastName_th")
    protected String responseLastNameTh;
    protected String responseLocation;
    @XmlElement(name = "responseLocationName_en")
    protected String responseLocationNameEn;
    @XmlElement(name = "responseLocationName_th")
    protected String responseLocationNameTh;
    protected String responseMobilePhone;
    @XmlElement(name = "responsePhone_en")
    protected String responsePhoneEn;
    @XmlElement(name = "responsePhone_th")
    protected String responsePhoneTh;
    @XmlElement(name = "responsePostal_en")
    protected String responsePostalEn;
    @XmlElement(name = "responsePostal_th")
    protected String responsePostalTh;
    @XmlElement(name = "responseProvinceName_en")
    protected String responseProvinceNameEn;
    @XmlElement(name = "responseProvinceName_th")
    protected String responseProvinceNameTh;
    protected String responseRankCode;
    @XmlElement(name = "responseRankName_en")
    protected String responseRankNameEn;
    @XmlElement(name = "responseRankName_th")
    protected String responseRankNameTh;
    @XmlElement(name = "responseTambon_en")
    protected String responseTambonEn;
    @XmlElement(name = "responseTambon_th")
    protected String responseTambonTh;
    @XmlElement(name = "responseTitle_en")
    protected String responseTitleEn;
    @XmlElement(name = "responseTitle_th")
    protected String responseTitleTh;

    /**
     * Gets the value of the headerRs property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderRs }
     *     
     */
    public HeaderRs getHeaderRs() {
        return headerRs;
    }

    /**
     * Sets the value of the headerRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderRs }
     *     
     */
    public void setHeaderRs(HeaderRs value) {
        this.headerRs = value;
    }

    /**
     * Gets the value of the itemList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KtbEmpBussinessCardList }
     * 
     * 
     */
    public List<KtbEmpBussinessCardList> getItemList() {
        if (itemList == null) {
            itemList = new ArrayList<KtbEmpBussinessCardList>();
        }
        return this.itemList;
    }

    /**
     * Gets the value of the responseAddress1En property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseAddress1En() {
        return responseAddress1En;
    }

    /**
     * Sets the value of the responseAddress1En property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseAddress1En(String value) {
        this.responseAddress1En = value;
    }

    /**
     * Gets the value of the responseAddress1Th property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseAddress1Th() {
        return responseAddress1Th;
    }

    /**
     * Sets the value of the responseAddress1Th property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseAddress1Th(String value) {
        this.responseAddress1Th = value;
    }

    /**
     * Gets the value of the responseAddress2En property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseAddress2En() {
        return responseAddress2En;
    }

    /**
     * Sets the value of the responseAddress2En property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseAddress2En(String value) {
        this.responseAddress2En = value;
    }

    /**
     * Gets the value of the responseAddress2Th property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseAddress2Th() {
        return responseAddress2Th;
    }

    /**
     * Sets the value of the responseAddress2Th property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseAddress2Th(String value) {
        this.responseAddress2Th = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the responseCostCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCostCenter() {
        return responseCostCenter;
    }

    /**
     * Sets the value of the responseCostCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCostCenter(String value) {
        this.responseCostCenter = value;
    }

    /**
     * Gets the value of the responseCostCenterDescrEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCostCenterDescrEn() {
        return responseCostCenterDescrEn;
    }

    /**
     * Sets the value of the responseCostCenterDescrEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCostCenterDescrEn(String value) {
        this.responseCostCenterDescrEn = value;
    }

    /**
     * Gets the value of the responseCostCenterDescrTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCostCenterDescrTh() {
        return responseCostCenterDescrTh;
    }

    /**
     * Sets the value of the responseCostCenterDescrTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCostCenterDescrTh(String value) {
        this.responseCostCenterDescrTh = value;
    }

    /**
     * Gets the value of the responseDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDescr() {
        return responseDescr;
    }

    /**
     * Sets the value of the responseDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDescr(String value) {
        this.responseDescr = value;
    }

    /**
     * Gets the value of the responseDistrictEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDistrictEn() {
        return responseDistrictEn;
    }

    /**
     * Sets the value of the responseDistrictEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDistrictEn(String value) {
        this.responseDistrictEn = value;
    }

    /**
     * Gets the value of the responseDistrictTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDistrictTh() {
        return responseDistrictTh;
    }

    /**
     * Sets the value of the responseDistrictTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDistrictTh(String value) {
        this.responseDistrictTh = value;
    }

    /**
     * Gets the value of the responseEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseEmail() {
        return responseEmail;
    }

    /**
     * Sets the value of the responseEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseEmail(String value) {
        this.responseEmail = value;
    }

    /**
     * Gets the value of the responseEmplRecordNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseEmplRecordNo() {
        return responseEmplRecordNo;
    }

    /**
     * Sets the value of the responseEmplRecordNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseEmplRecordNo(String value) {
        this.responseEmplRecordNo = value;
    }

    /**
     * Gets the value of the responseEmplid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseEmplid() {
        return responseEmplid;
    }

    /**
     * Sets the value of the responseEmplid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseEmplid(String value) {
        this.responseEmplid = value;
    }

    /**
     * Gets the value of the responseFaxEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseFaxEn() {
        return responseFaxEn;
    }

    /**
     * Sets the value of the responseFaxEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseFaxEn(String value) {
        this.responseFaxEn = value;
    }

    /**
     * Gets the value of the responseFaxTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseFaxTh() {
        return responseFaxTh;
    }

    /**
     * Sets the value of the responseFaxTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseFaxTh(String value) {
        this.responseFaxTh = value;
    }

    /**
     * Gets the value of the responseFirstNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseFirstNameEn() {
        return responseFirstNameEn;
    }

    /**
     * Sets the value of the responseFirstNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseFirstNameEn(String value) {
        this.responseFirstNameEn = value;
    }

    /**
     * Gets the value of the responseFirstNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseFirstNameTh() {
        return responseFirstNameTh;
    }

    /**
     * Sets the value of the responseFirstNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseFirstNameTh(String value) {
        this.responseFirstNameTh = value;
    }

    /**
     * Gets the value of the responseLastNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseLastNameEn() {
        return responseLastNameEn;
    }

    /**
     * Sets the value of the responseLastNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseLastNameEn(String value) {
        this.responseLastNameEn = value;
    }

    /**
     * Gets the value of the responseLastNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseLastNameTh() {
        return responseLastNameTh;
    }

    /**
     * Sets the value of the responseLastNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseLastNameTh(String value) {
        this.responseLastNameTh = value;
    }

    /**
     * Gets the value of the responseLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseLocation() {
        return responseLocation;
    }

    /**
     * Sets the value of the responseLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseLocation(String value) {
        this.responseLocation = value;
    }

    /**
     * Gets the value of the responseLocationNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseLocationNameEn() {
        return responseLocationNameEn;
    }

    /**
     * Sets the value of the responseLocationNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseLocationNameEn(String value) {
        this.responseLocationNameEn = value;
    }

    /**
     * Gets the value of the responseLocationNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseLocationNameTh() {
        return responseLocationNameTh;
    }

    /**
     * Sets the value of the responseLocationNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseLocationNameTh(String value) {
        this.responseLocationNameTh = value;
    }

    /**
     * Gets the value of the responseMobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMobilePhone() {
        return responseMobilePhone;
    }

    /**
     * Sets the value of the responseMobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMobilePhone(String value) {
        this.responseMobilePhone = value;
    }

    /**
     * Gets the value of the responsePhoneEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsePhoneEn() {
        return responsePhoneEn;
    }

    /**
     * Sets the value of the responsePhoneEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsePhoneEn(String value) {
        this.responsePhoneEn = value;
    }

    /**
     * Gets the value of the responsePhoneTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsePhoneTh() {
        return responsePhoneTh;
    }

    /**
     * Sets the value of the responsePhoneTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsePhoneTh(String value) {
        this.responsePhoneTh = value;
    }

    /**
     * Gets the value of the responsePostalEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsePostalEn() {
        return responsePostalEn;
    }

    /**
     * Sets the value of the responsePostalEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsePostalEn(String value) {
        this.responsePostalEn = value;
    }

    /**
     * Gets the value of the responsePostalTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsePostalTh() {
        return responsePostalTh;
    }

    /**
     * Sets the value of the responsePostalTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsePostalTh(String value) {
        this.responsePostalTh = value;
    }

    /**
     * Gets the value of the responseProvinceNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseProvinceNameEn() {
        return responseProvinceNameEn;
    }

    /**
     * Sets the value of the responseProvinceNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseProvinceNameEn(String value) {
        this.responseProvinceNameEn = value;
    }

    /**
     * Gets the value of the responseProvinceNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseProvinceNameTh() {
        return responseProvinceNameTh;
    }

    /**
     * Sets the value of the responseProvinceNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseProvinceNameTh(String value) {
        this.responseProvinceNameTh = value;
    }

    /**
     * Gets the value of the responseRankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseRankCode() {
        return responseRankCode;
    }

    /**
     * Sets the value of the responseRankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseRankCode(String value) {
        this.responseRankCode = value;
    }

    /**
     * Gets the value of the responseRankNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseRankNameEn() {
        return responseRankNameEn;
    }

    /**
     * Sets the value of the responseRankNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseRankNameEn(String value) {
        this.responseRankNameEn = value;
    }

    /**
     * Gets the value of the responseRankNameTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseRankNameTh() {
        return responseRankNameTh;
    }

    /**
     * Sets the value of the responseRankNameTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseRankNameTh(String value) {
        this.responseRankNameTh = value;
    }

    /**
     * Gets the value of the responseTambonEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseTambonEn() {
        return responseTambonEn;
    }

    /**
     * Sets the value of the responseTambonEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseTambonEn(String value) {
        this.responseTambonEn = value;
    }

    /**
     * Gets the value of the responseTambonTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseTambonTh() {
        return responseTambonTh;
    }

    /**
     * Sets the value of the responseTambonTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseTambonTh(String value) {
        this.responseTambonTh = value;
    }

    /**
     * Gets the value of the responseTitleEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseTitleEn() {
        return responseTitleEn;
    }

    /**
     * Sets the value of the responseTitleEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseTitleEn(String value) {
        this.responseTitleEn = value;
    }

    /**
     * Gets the value of the responseTitleTh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseTitleTh() {
        return responseTitleTh;
    }

    /**
     * Sets the value of the responseTitleTh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseTitleTh(String value) {
        this.responseTitleTh = value;
    }

}
