//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ktbGetConsentMsgList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ktbGetConsentMsgList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:EmployeeWS/types}hrmSsystem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="p_MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="p_RESULT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ktbGetConsentMsgList", propOrder = {
    "pmessage",
    "presult"
})
public class KtbGetConsentMsgList
    extends HrmSsystem
{

    @XmlElement(name = "p_MESSAGE")
    protected String pmessage;
    @XmlElement(name = "p_RESULT")
    protected String presult;

    /**
     * Gets the value of the pmessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPMESSAGE() {
        return pmessage;
    }

    /**
     * Sets the value of the pmessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMESSAGE(String value) {
        this.pmessage = value;
    }

    /**
     * Gets the value of the presult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRESULT() {
        return presult;
    }

    /**
     * Sets the value of the presult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRESULT(String value) {
        this.presult = value;
    }

}
