//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ktbGetPolicyList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ktbGetPolicyList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:EmployeeWS/types}hrmSsystem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="activeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="createBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbDescr1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbEffdt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbEnddt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbOpendt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastUpdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastUpdateBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="versionNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ktbGetPolicyList", propOrder = {
    "activeFlag",
    "createBy",
    "createDate",
    "ktbDescr1",
    "ktbEffdt",
    "ktbEnddt",
    "ktbId",
    "ktbOpendt",
    "lastUpdate",
    "lastUpdateBy",
    "versionNo"
})
public class KtbGetPolicyList
    extends HrmSsystem
{

    protected String activeFlag;
    protected String createBy;
    protected String createDate;
    protected String ktbDescr1;
    protected String ktbEffdt;
    protected String ktbEnddt;
    protected String ktbId;
    protected String ktbOpendt;
    protected String lastUpdate;
    protected String lastUpdateBy;
    protected String versionNo;

    /**
     * Gets the value of the activeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFlag(String value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the createBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * Sets the value of the createBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateBy(String value) {
        this.createBy = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDate(String value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the ktbDescr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbDescr1() {
        return ktbDescr1;
    }

    /**
     * Sets the value of the ktbDescr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbDescr1(String value) {
        this.ktbDescr1 = value;
    }

    /**
     * Gets the value of the ktbEffdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbEffdt() {
        return ktbEffdt;
    }

    /**
     * Sets the value of the ktbEffdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbEffdt(String value) {
        this.ktbEffdt = value;
    }

    /**
     * Gets the value of the ktbEnddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbEnddt() {
        return ktbEnddt;
    }

    /**
     * Sets the value of the ktbEnddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbEnddt(String value) {
        this.ktbEnddt = value;
    }

    /**
     * Gets the value of the ktbId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbId() {
        return ktbId;
    }

    /**
     * Sets the value of the ktbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbId(String value) {
        this.ktbId = value;
    }

    /**
     * Gets the value of the ktbOpendt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbOpendt() {
        return ktbOpendt;
    }

    /**
     * Sets the value of the ktbOpendt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbOpendt(String value) {
        this.ktbOpendt = value;
    }

    /**
     * Gets the value of the lastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets the value of the lastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdate(String value) {
        this.lastUpdate = value;
    }

    /**
     * Gets the value of the lastUpdateBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * Sets the value of the lastUpdateBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateBy(String value) {
        this.lastUpdateBy = value;
    }

    /**
     * Gets the value of the versionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * Sets the value of the versionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionNo(String value) {
        this.versionNo = value;
    }

}
