//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ktbGetConsentList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ktbGetConsentList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:EmployeeWS/types}hrmSsystem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="activeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="consentAnsFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="footerDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="headerDescr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbEffdt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbEnddt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ktbOpendt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="questionDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="questionFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="questionNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="questionNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="versionNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="viewConsent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ktbGetConsentList", propOrder = {
    "activeFlag",
    "consentAnsFlag",
    "footerDesc",
    "headerDescr",
    "ktbEffdt",
    "ktbEnddt",
    "ktbId",
    "ktbOpendt",
    "questionDesc",
    "questionFlag",
    "questionNote",
    "questionNum",
    "seqNum",
    "versionNo",
    "viewConsent"
})
public class KtbGetConsentList
    extends HrmSsystem
{

    protected String activeFlag;
    protected String consentAnsFlag;
    protected String footerDesc;
    protected String headerDescr;
    protected String ktbEffdt;
    protected String ktbEnddt;
    protected String ktbId;
    protected String ktbOpendt;
    protected String questionDesc;
    protected String questionFlag;
    protected String questionNote;
    protected String questionNum;
    protected String seqNum;
    protected String versionNo;
    protected String viewConsent;

    /**
     * Gets the value of the activeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFlag(String value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the consentAnsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsentAnsFlag() {
        return consentAnsFlag;
    }

    /**
     * Sets the value of the consentAnsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsentAnsFlag(String value) {
        this.consentAnsFlag = value;
    }

    /**
     * Gets the value of the footerDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFooterDesc() {
        return footerDesc;
    }

    /**
     * Sets the value of the footerDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFooterDesc(String value) {
        this.footerDesc = value;
    }

    /**
     * Gets the value of the headerDescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderDescr() {
        return headerDescr;
    }

    /**
     * Sets the value of the headerDescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderDescr(String value) {
        this.headerDescr = value;
    }

    /**
     * Gets the value of the ktbEffdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbEffdt() {
        return ktbEffdt;
    }

    /**
     * Sets the value of the ktbEffdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbEffdt(String value) {
        this.ktbEffdt = value;
    }

    /**
     * Gets the value of the ktbEnddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbEnddt() {
        return ktbEnddt;
    }

    /**
     * Sets the value of the ktbEnddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbEnddt(String value) {
        this.ktbEnddt = value;
    }

    /**
     * Gets the value of the ktbId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbId() {
        return ktbId;
    }

    /**
     * Sets the value of the ktbId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbId(String value) {
        this.ktbId = value;
    }

    /**
     * Gets the value of the ktbOpendt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKtbOpendt() {
        return ktbOpendt;
    }

    /**
     * Sets the value of the ktbOpendt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKtbOpendt(String value) {
        this.ktbOpendt = value;
    }

    /**
     * Gets the value of the questionDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionDesc() {
        return questionDesc;
    }

    /**
     * Sets the value of the questionDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionDesc(String value) {
        this.questionDesc = value;
    }

    /**
     * Gets the value of the questionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionFlag() {
        return questionFlag;
    }

    /**
     * Sets the value of the questionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionFlag(String value) {
        this.questionFlag = value;
    }

    /**
     * Gets the value of the questionNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionNote() {
        return questionNote;
    }

    /**
     * Sets the value of the questionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionNote(String value) {
        this.questionNote = value;
    }

    /**
     * Gets the value of the questionNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionNum() {
        return questionNum;
    }

    /**
     * Sets the value of the questionNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionNum(String value) {
        this.questionNum = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNum(String value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the versionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * Sets the value of the versionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionNo(String value) {
        this.versionNo = value;
    }

    /**
     * Gets the value of the viewConsent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewConsent() {
        return viewConsent;
    }

    /**
     * Sets the value of the viewConsent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewConsent(String value) {
        this.viewConsent = value;
    }

}
