//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.05 at 02:15:55 PM ICT 
//


package com.ws.hrms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ws.hrms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetConsent_QNAME = new QName("urn:EmployeeWS/types", "GetConsent");
    private final static QName _GetConsentResponse_QNAME = new QName("urn:EmployeeWS/types", "GetConsentResponse");
    private final static QName _GetEmpByEmail_QNAME = new QName("urn:EmployeeWS/types", "GetEmpByEmail");
    private final static QName _GetEmpByEmailResponse_QNAME = new QName("urn:EmployeeWS/types", "GetEmpByEmailResponse");
    private final static QName _GetEmpConsentFlag_QNAME = new QName("urn:EmployeeWS/types", "GetEmpConsentFlag");
    private final static QName _GetEmpConsentFlagResponse_QNAME = new QName("urn:EmployeeWS/types", "GetEmpConsentFlagResponse");
    private final static QName _GetPolicyAll_QNAME = new QName("urn:EmployeeWS/types", "GetPolicyAll");
    private final static QName _GetPolicyAllResponse_QNAME = new QName("urn:EmployeeWS/types", "GetPolicyAllResponse");
    private final static QName _InsertConsent_QNAME = new QName("urn:EmployeeWS/types", "InsertConsent");
    private final static QName _InsertConsentResponse_QNAME = new QName("urn:EmployeeWS/types", "InsertConsentResponse");
    private final static QName _GetEmpAbsence_QNAME = new QName("urn:EmployeeWS/types", "getEmpAbsence");
    private final static QName _GetEmpAbsenceResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpAbsenceResponse");
    private final static QName _GetEmpBusinessCard_QNAME = new QName("urn:EmployeeWS/types", "getEmpBusinessCard");
    private final static QName _GetEmpBusinessCardResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpBusinessCardResponse");
    private final static QName _GetEmpContact_QNAME = new QName("urn:EmployeeWS/types", "getEmpContact");
    private final static QName _GetEmpContactResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpContactResponse");
    private final static QName _GetEmpName_QNAME = new QName("urn:EmployeeWS/types", "getEmpName");
    private final static QName _GetEmpNameResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpNameResponse");
    private final static QName _GetEmpPhoto_QNAME = new QName("urn:EmployeeWS/types", "getEmpPhoto");
    private final static QName _GetEmpPhotoList_QNAME = new QName("urn:EmployeeWS/types", "getEmpPhotoList");
    private final static QName _GetEmpPhotoListProc_QNAME = new QName("urn:EmployeeWS/types", "getEmpPhotoListProc");
    private final static QName _GetEmpPhotoListProcResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpPhotoListProcResponse");
    private final static QName _GetEmpPhotoListResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpPhotoListResponse");
    private final static QName _GetEmpPhotoResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpPhotoResponse");
    private final static QName _GetEmpRC_QNAME = new QName("urn:EmployeeWS/types", "getEmpRC");
    private final static QName _GetEmpRCResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpRCResponse");
    private final static QName _GetEmpSignDetail_QNAME = new QName("urn:EmployeeWS/types", "getEmpSignDetail");
    private final static QName _GetEmpSignDetailResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmpSignDetailResponse");
    private final static QName _GetEmployee_QNAME = new QName("urn:EmployeeWS/types", "getEmployee");
    private final static QName _GetEmployeeAll_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeAll");
    private final static QName _GetEmployeeAllResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeAllResponse");
    private final static QName _GetEmployeeByCitizenOrEmplid_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeByCitizenOrEmplid");
    private final static QName _GetEmployeeByCitizenOrEmplidResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeByCitizenOrEmplidResponse");
    private final static QName _GetEmployeeByName_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeByName");
    private final static QName _GetEmployeeByNameResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeByNameResponse");
    private final static QName _GetEmployeeByRankOrCostCenter_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeByRankOrCostCenter");
    private final static QName _GetEmployeeByRankOrCostCenterResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeByRankOrCostCenterResponse");
    private final static QName _GetEmployeeDetail_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeDetail");
    private final static QName _GetEmployeeDetailResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeDetailResponse");
    private final static QName _GetEmployeeInfo_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeInfo");
    private final static QName _GetEmployeeInfoResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeInfoResponse");
    private final static QName _GetEmployeeResponse_QNAME = new QName("urn:EmployeeWS/types", "getEmployeeResponse");
    private final static QName _GetLicense_QNAME = new QName("urn:EmployeeWS/types", "getLicense");
    private final static QName _GetLicenseInfo_QNAME = new QName("urn:EmployeeWS/types", "getLicenseInfo");
    private final static QName _GetLicenseInfoResponse_QNAME = new QName("urn:EmployeeWS/types", "getLicenseInfoResponse");
    private final static QName _GetLicenseResponse_QNAME = new QName("urn:EmployeeWS/types", "getLicenseResponse");
    private final static QName _GetLicenseSub_QNAME = new QName("urn:EmployeeWS/types", "getLicenseSub");
    private final static QName _GetLicenseSubResponse_QNAME = new QName("urn:EmployeeWS/types", "getLicenseSubResponse");
    private final static QName _GetLicenseType_QNAME = new QName("urn:EmployeeWS/types", "getLicenseType");
    private final static QName _GetLicenseTypeResponse_QNAME = new QName("urn:EmployeeWS/types", "getLicenseTypeResponse");
    private final static QName _GetReportTo_QNAME = new QName("urn:EmployeeWS/types", "getReportTo");
    private final static QName _GetReportToResponse_QNAME = new QName("urn:EmployeeWS/types", "getReportToResponse");
    private final static QName _Exception_QNAME = new QName("urn:EmployeeWS/types", "Exception");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ws.hrms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetConsent }
     * 
     */
    public GetConsent createGetConsent() {
        return new GetConsent();
    }

    /**
     * Create an instance of {@link GetConsentResponse }
     * 
     */
    public GetConsentResponse createGetConsentResponse() {
        return new GetConsentResponse();
    }

    /**
     * Create an instance of {@link GetEmpByEmail }
     * 
     */
    public GetEmpByEmail createGetEmpByEmail() {
        return new GetEmpByEmail();
    }

    /**
     * Create an instance of {@link GetEmpByEmailResponse }
     * 
     */
    public GetEmpByEmailResponse createGetEmpByEmailResponse() {
        return new GetEmpByEmailResponse();
    }

    /**
     * Create an instance of {@link GetEmpConsentFlag }
     * 
     */
    public GetEmpConsentFlag createGetEmpConsentFlag() {
        return new GetEmpConsentFlag();
    }

    /**
     * Create an instance of {@link GetEmpConsentFlagResponse }
     * 
     */
    public GetEmpConsentFlagResponse createGetEmpConsentFlagResponse() {
        return new GetEmpConsentFlagResponse();
    }

    /**
     * Create an instance of {@link GetPolicyAll }
     * 
     */
    public GetPolicyAll createGetPolicyAll() {
        return new GetPolicyAll();
    }

    /**
     * Create an instance of {@link GetPolicyAllResponse }
     * 
     */
    public GetPolicyAllResponse createGetPolicyAllResponse() {
        return new GetPolicyAllResponse();
    }

    /**
     * Create an instance of {@link InsertConsent }
     * 
     */
    public InsertConsent createInsertConsent() {
        return new InsertConsent();
    }

    /**
     * Create an instance of {@link InsertConsentResponse }
     * 
     */
    public InsertConsentResponse createInsertConsentResponse() {
        return new InsertConsentResponse();
    }

    /**
     * Create an instance of {@link GetEmpAbsence }
     * 
     */
    public GetEmpAbsence createGetEmpAbsence() {
        return new GetEmpAbsence();
    }

    /**
     * Create an instance of {@link GetEmpAbsenceResponse }
     * 
     */
    public GetEmpAbsenceResponse createGetEmpAbsenceResponse() {
        return new GetEmpAbsenceResponse();
    }

    /**
     * Create an instance of {@link GetEmpBusinessCard }
     * 
     */
    public GetEmpBusinessCard createGetEmpBusinessCard() {
        return new GetEmpBusinessCard();
    }

    /**
     * Create an instance of {@link GetEmpBusinessCardResponse }
     * 
     */
    public GetEmpBusinessCardResponse createGetEmpBusinessCardResponse() {
        return new GetEmpBusinessCardResponse();
    }

    /**
     * Create an instance of {@link GetEmpContact }
     * 
     */
    public GetEmpContact createGetEmpContact() {
        return new GetEmpContact();
    }

    /**
     * Create an instance of {@link GetEmpContactResponse }
     * 
     */
    public GetEmpContactResponse createGetEmpContactResponse() {
        return new GetEmpContactResponse();
    }

    /**
     * Create an instance of {@link GetEmpName }
     * 
     */
    public GetEmpName createGetEmpName() {
        return new GetEmpName();
    }

    /**
     * Create an instance of {@link GetEmpNameResponse }
     * 
     */
    public GetEmpNameResponse createGetEmpNameResponse() {
        return new GetEmpNameResponse();
    }

    /**
     * Create an instance of {@link GetEmpPhoto }
     * 
     */
    public GetEmpPhoto createGetEmpPhoto() {
        return new GetEmpPhoto();
    }

    /**
     * Create an instance of {@link GetEmpPhotoList }
     * 
     */
    public GetEmpPhotoList createGetEmpPhotoList() {
        return new GetEmpPhotoList();
    }

    /**
     * Create an instance of {@link GetEmpPhotoListProc }
     * 
     */
    public GetEmpPhotoListProc createGetEmpPhotoListProc() {
        return new GetEmpPhotoListProc();
    }

    /**
     * Create an instance of {@link GetEmpPhotoListProcResponse }
     * 
     */
    public GetEmpPhotoListProcResponse createGetEmpPhotoListProcResponse() {
        return new GetEmpPhotoListProcResponse();
    }

    /**
     * Create an instance of {@link GetEmpPhotoListResponse }
     * 
     */
    public GetEmpPhotoListResponse createGetEmpPhotoListResponse() {
        return new GetEmpPhotoListResponse();
    }

    /**
     * Create an instance of {@link GetEmpPhotoResponse }
     * 
     */
    public GetEmpPhotoResponse createGetEmpPhotoResponse() {
        return new GetEmpPhotoResponse();
    }

    /**
     * Create an instance of {@link GetEmpRC }
     * 
     */
    public GetEmpRC createGetEmpRC() {
        return new GetEmpRC();
    }

    /**
     * Create an instance of {@link GetEmpRCResponse }
     * 
     */
    public GetEmpRCResponse createGetEmpRCResponse() {
        return new GetEmpRCResponse();
    }

    /**
     * Create an instance of {@link GetEmpSignDetail }
     * 
     */
    public GetEmpSignDetail createGetEmpSignDetail() {
        return new GetEmpSignDetail();
    }

    /**
     * Create an instance of {@link GetEmpSignDetailResponse }
     * 
     */
    public GetEmpSignDetailResponse createGetEmpSignDetailResponse() {
        return new GetEmpSignDetailResponse();
    }

    /**
     * Create an instance of {@link GetEmployee }
     * 
     */
    public GetEmployee createGetEmployee() {
        return new GetEmployee();
    }

    /**
     * Create an instance of {@link GetEmployeeAll }
     * 
     */
    public GetEmployeeAll createGetEmployeeAll() {
        return new GetEmployeeAll();
    }

    /**
     * Create an instance of {@link GetEmployeeAllResponse }
     * 
     */
    public GetEmployeeAllResponse createGetEmployeeAllResponse() {
        return new GetEmployeeAllResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeByCitizenOrEmplid }
     * 
     */
    public GetEmployeeByCitizenOrEmplid createGetEmployeeByCitizenOrEmplid() {
        return new GetEmployeeByCitizenOrEmplid();
    }

    /**
     * Create an instance of {@link GetEmployeeByCitizenOrEmplidResponse }
     * 
     */
    public GetEmployeeByCitizenOrEmplidResponse createGetEmployeeByCitizenOrEmplidResponse() {
        return new GetEmployeeByCitizenOrEmplidResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeByName }
     * 
     */
    public GetEmployeeByName createGetEmployeeByName() {
        return new GetEmployeeByName();
    }

    /**
     * Create an instance of {@link GetEmployeeByNameResponse }
     * 
     */
    public GetEmployeeByNameResponse createGetEmployeeByNameResponse() {
        return new GetEmployeeByNameResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeByRankOrCostCenter }
     * 
     */
    public GetEmployeeByRankOrCostCenter createGetEmployeeByRankOrCostCenter() {
        return new GetEmployeeByRankOrCostCenter();
    }

    /**
     * Create an instance of {@link GetEmployeeByRankOrCostCenterResponse }
     * 
     */
    public GetEmployeeByRankOrCostCenterResponse createGetEmployeeByRankOrCostCenterResponse() {
        return new GetEmployeeByRankOrCostCenterResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeDetail }
     * 
     */
    public GetEmployeeDetail createGetEmployeeDetail() {
        return new GetEmployeeDetail();
    }

    /**
     * Create an instance of {@link GetEmployeeDetailResponse }
     * 
     */
    public GetEmployeeDetailResponse createGetEmployeeDetailResponse() {
        return new GetEmployeeDetailResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeInfo }
     * 
     */
    public GetEmployeeInfo createGetEmployeeInfo() {
        return new GetEmployeeInfo();
    }

    /**
     * Create an instance of {@link GetEmployeeInfoResponse }
     * 
     */
    public GetEmployeeInfoResponse createGetEmployeeInfoResponse() {
        return new GetEmployeeInfoResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeResponse }
     * 
     */
    public GetEmployeeResponse createGetEmployeeResponse() {
        return new GetEmployeeResponse();
    }

    /**
     * Create an instance of {@link GetLicense }
     * 
     */
    public GetLicense createGetLicense() {
        return new GetLicense();
    }

    /**
     * Create an instance of {@link GetLicenseInfo }
     * 
     */
    public GetLicenseInfo createGetLicenseInfo() {
        return new GetLicenseInfo();
    }

    /**
     * Create an instance of {@link GetLicenseInfoResponse }
     * 
     */
    public GetLicenseInfoResponse createGetLicenseInfoResponse() {
        return new GetLicenseInfoResponse();
    }

    /**
     * Create an instance of {@link GetLicenseResponse }
     * 
     */
    public GetLicenseResponse createGetLicenseResponse() {
        return new GetLicenseResponse();
    }

    /**
     * Create an instance of {@link GetLicenseSub }
     * 
     */
    public GetLicenseSub createGetLicenseSub() {
        return new GetLicenseSub();
    }

    /**
     * Create an instance of {@link GetLicenseSubResponse }
     * 
     */
    public GetLicenseSubResponse createGetLicenseSubResponse() {
        return new GetLicenseSubResponse();
    }

    /**
     * Create an instance of {@link GetLicenseType }
     * 
     */
    public GetLicenseType createGetLicenseType() {
        return new GetLicenseType();
    }

    /**
     * Create an instance of {@link GetLicenseTypeResponse }
     * 
     */
    public GetLicenseTypeResponse createGetLicenseTypeResponse() {
        return new GetLicenseTypeResponse();
    }

    /**
     * Create an instance of {@link GetReportTo }
     * 
     */
    public GetReportTo createGetReportTo() {
        return new GetReportTo();
    }

    /**
     * Create an instance of {@link GetReportToResponse }
     * 
     */
    public GetReportToResponse createGetReportToResponse() {
        return new GetReportToResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link KtbGetEmpByEmailRequestList }
     * 
     */
    public KtbGetEmpByEmailRequestList createKtbGetEmpByEmailRequestList() {
        return new KtbGetEmpByEmailRequestList();
    }

    /**
     * Create an instance of {@link KtbGetEmpByEmailRes }
     * 
     */
    public KtbGetEmpByEmailRes createKtbGetEmpByEmailRes() {
        return new KtbGetEmpByEmailRes();
    }

    /**
     * Create an instance of {@link KtbGetEmpByEmailList }
     * 
     */
    public KtbGetEmpByEmailList createKtbGetEmpByEmailList() {
        return new KtbGetEmpByEmailList();
    }

    /**
     * Create an instance of {@link HeaderRq }
     * 
     */
    public HeaderRq createHeaderRq() {
        return new HeaderRq();
    }

    /**
     * Create an instance of {@link KtbReqLicSub }
     * 
     */
    public KtbReqLicSub createKtbReqLicSub() {
        return new KtbReqLicSub();
    }

    /**
     * Create an instance of {@link KtbResLicSub }
     * 
     */
    public KtbResLicSub createKtbResLicSub() {
        return new KtbResLicSub();
    }

    /**
     * Create an instance of {@link GetLicenseRq }
     * 
     */
    public GetLicenseRq createGetLicenseRq() {
        return new GetLicenseRq();
    }

    /**
     * Create an instance of {@link GetLicenseRs }
     * 
     */
    public GetLicenseRs createGetLicenseRs() {
        return new GetLicenseRs();
    }

    /**
     * Create an instance of {@link HeaderRs }
     * 
     */
    public HeaderRs createHeaderRs() {
        return new HeaderRs();
    }

    /**
     * Create an instance of {@link KtbEmpBussinessCardRq }
     * 
     */
    public KtbEmpBussinessCardRq createKtbEmpBussinessCardRq() {
        return new KtbEmpBussinessCardRq();
    }

    /**
     * Create an instance of {@link KtbEmpBussinessCardRes }
     * 
     */
    public KtbEmpBussinessCardRes createKtbEmpBussinessCardRes() {
        return new KtbEmpBussinessCardRes();
    }

    /**
     * Create an instance of {@link KtbEmpBussinessCardList }
     * 
     */
    public KtbEmpBussinessCardList createKtbEmpBussinessCardList() {
        return new KtbEmpBussinessCardList();
    }

    /**
     * Create an instance of {@link KtbEmployeeWS2 }
     * 
     */
    public KtbEmployeeWS2 createKtbEmployeeWS2() {
        return new KtbEmployeeWS2();
    }

    /**
     * Create an instance of {@link KtbEmployee }
     * 
     */
    public KtbEmployee createKtbEmployee() {
        return new KtbEmployee();
    }

    /**
     * Create an instance of {@link ConsentInsertrq }
     * 
     */
    public ConsentInsertrq createConsentInsertrq() {
        return new ConsentInsertrq();
    }

    /**
     * Create an instance of {@link KtbGetConsentRes }
     * 
     */
    public KtbGetConsentRes createKtbGetConsentRes() {
        return new KtbGetConsentRes();
    }

    /**
     * Create an instance of {@link KtbGetConsentFlagList }
     * 
     */
    public KtbGetConsentFlagList createKtbGetConsentFlagList() {
        return new KtbGetConsentFlagList();
    }

    /**
     * Create an instance of {@link KtbGetConsentList }
     * 
     */
    public KtbGetConsentList createKtbGetConsentList() {
        return new KtbGetConsentList();
    }

    /**
     * Create an instance of {@link KtbGetConsentMsgList }
     * 
     */
    public KtbGetConsentMsgList createKtbGetConsentMsgList() {
        return new KtbGetConsentMsgList();
    }

    /**
     * Create an instance of {@link ConsentRetrieveFlagRq }
     * 
     */
    public ConsentRetrieveFlagRq createConsentRetrieveFlagRq() {
        return new ConsentRetrieveFlagRq();
    }

    /**
     * Create an instance of {@link KtbGetConsentFlagRes }
     * 
     */
    public KtbGetConsentFlagRes createKtbGetConsentFlagRes() {
        return new KtbGetConsentFlagRes();
    }

    /**
     * Create an instance of {@link KtbEmployeeWS }
     * 
     */
    public KtbEmployeeWS createKtbEmployeeWS() {
        return new KtbEmployeeWS();
    }

    /**
     * Create an instance of {@link KtbEmployeeInfo }
     * 
     */
    public KtbEmployeeInfo createKtbEmployeeInfo() {
        return new KtbEmployeeInfo();
    }

    /**
     * Create an instance of {@link EmployeeReq }
     * 
     */
    public EmployeeReq createEmployeeReq() {
        return new EmployeeReq();
    }

    /**
     * Create an instance of {@link EmployeeByCitizenIDOrEmplidRes }
     * 
     */
    public EmployeeByCitizenIDOrEmplidRes createEmployeeByCitizenIDOrEmplidRes() {
        return new EmployeeByCitizenIDOrEmplidRes();
    }

    /**
     * Create an instance of {@link KtbEmpAbsRq }
     * 
     */
    public KtbEmpAbsRq createKtbEmpAbsRq() {
        return new KtbEmpAbsRq();
    }

    /**
     * Create an instance of {@link KtbEmpAbsRes }
     * 
     */
    public KtbEmpAbsRes createKtbEmpAbsRes() {
        return new KtbEmpAbsRes();
    }

    /**
     * Create an instance of {@link KtbGetPolicyRequestList }
     * 
     */
    public KtbGetPolicyRequestList createKtbGetPolicyRequestList() {
        return new KtbGetPolicyRequestList();
    }

    /**
     * Create an instance of {@link KtbGetPolicyRes }
     * 
     */
    public KtbGetPolicyRes createKtbGetPolicyRes() {
        return new KtbGetPolicyRes();
    }

    /**
     * Create an instance of {@link KtbGetPolicyList }
     * 
     */
    public KtbGetPolicyList createKtbGetPolicyList() {
        return new KtbGetPolicyList();
    }

    /**
     * Create an instance of {@link KtbEmployeeByRankOrCostCenterRq }
     * 
     */
    public KtbEmployeeByRankOrCostCenterRq createKtbEmployeeByRankOrCostCenterRq() {
        return new KtbEmployeeByRankOrCostCenterRq();
    }

    /**
     * Create an instance of {@link KtbEmployeeByRankOrCostCenter }
     * 
     */
    public KtbEmployeeByRankOrCostCenter createKtbEmployeeByRankOrCostCenter() {
        return new KtbEmployeeByRankOrCostCenter();
    }

    /**
     * Create an instance of {@link KtbEmployeeByRankOrCostCenterList }
     * 
     */
    public KtbEmployeeByRankOrCostCenterList createKtbEmployeeByRankOrCostCenterList() {
        return new KtbEmployeeByRankOrCostCenterList();
    }

    /**
     * Create an instance of {@link KtbEmployeeDetail }
     * 
     */
    public KtbEmployeeDetail createKtbEmployeeDetail() {
        return new KtbEmployeeDetail();
    }

    /**
     * Create an instance of {@link KtbLicenseInfoRq }
     * 
     */
    public KtbLicenseInfoRq createKtbLicenseInfoRq() {
        return new KtbLicenseInfoRq();
    }

    /**
     * Create an instance of {@link KtbLicenseInfoRes }
     * 
     */
    public KtbLicenseInfoRes createKtbLicenseInfoRes() {
        return new KtbLicenseInfoRes();
    }

    /**
     * Create an instance of {@link KtbLicenseInfoList }
     * 
     */
    public KtbLicenseInfoList createKtbLicenseInfoList() {
        return new KtbLicenseInfoList();
    }

    /**
     * Create an instance of {@link GetEmpNameRq }
     * 
     */
    public GetEmpNameRq createGetEmpNameRq() {
        return new GetEmpNameRq();
    }

    /**
     * Create an instance of {@link GetEmpNameRs }
     * 
     */
    public GetEmpNameRs createGetEmpNameRs() {
        return new GetEmpNameRs();
    }

    /**
     * Create an instance of {@link KtbEmpPhotoRq }
     * 
     */
    public KtbEmpPhotoRq createKtbEmpPhotoRq() {
        return new KtbEmpPhotoRq();
    }

    /**
     * Create an instance of {@link KtbEmpPhotoRes }
     * 
     */
    public KtbEmpPhotoRes createKtbEmpPhotoRes() {
        return new KtbEmpPhotoRes();
    }

    /**
     * Create an instance of {@link KtbReqLic }
     * 
     */
    public KtbReqLic createKtbReqLic() {
        return new KtbReqLic();
    }

    /**
     * Create an instance of {@link KtbResLic }
     * 
     */
    public KtbResLic createKtbResLic() {
        return new KtbResLic();
    }

    /**
     * Create an instance of {@link KtbLicSub }
     * 
     */
    public KtbLicSub createKtbLicSub() {
        return new KtbLicSub();
    }

    /**
     * Create an instance of {@link GetEmpRCRq }
     * 
     */
    public GetEmpRCRq createGetEmpRCRq() {
        return new GetEmpRCRq();
    }

    /**
     * Create an instance of {@link GetEmpRCRs }
     * 
     */
    public GetEmpRCRs createGetEmpRCRs() {
        return new GetEmpRCRs();
    }

    /**
     * Create an instance of {@link KtbEmpSignDetailRq }
     * 
     */
    public KtbEmpSignDetailRq createKtbEmpSignDetailRq() {
        return new KtbEmpSignDetailRq();
    }

    /**
     * Create an instance of {@link KtbEmpSignDetailRes }
     * 
     */
    public KtbEmpSignDetailRes createKtbEmpSignDetailRes() {
        return new KtbEmpSignDetailRes();
    }

    /**
     * Create an instance of {@link KtbEmpPhoto }
     * 
     */
    public KtbEmpPhoto createKtbEmpPhoto() {
        return new KtbEmpPhoto();
    }

    /**
     * Create an instance of {@link ConsentRetrieverq }
     * 
     */
    public ConsentRetrieverq createConsentRetrieverq() {
        return new ConsentRetrieverq();
    }

    /**
     * Create an instance of {@link KtbEmpContactRq }
     * 
     */
    public KtbEmpContactRq createKtbEmpContactRq() {
        return new KtbEmpContactRq();
    }

    /**
     * Create an instance of {@link KtbEmpContactRes }
     * 
     */
    public KtbEmpContactRes createKtbEmpContactRes() {
        return new KtbEmpContactRes();
    }

    /**
     * Create an instance of {@link KtbEmpReportTo }
     * 
     */
    public KtbEmpReportTo createKtbEmpReportTo() {
        return new KtbEmpReportTo();
    }

    /**
     * Create an instance of {@link KtbHRMSResponse }
     * 
     */
    public KtbHRMSResponse createKtbHRMSResponse() {
        return new KtbHRMSResponse();
    }

    /**
     * Create an instance of {@link KtbEmpPhotoListRq }
     * 
     */
    public KtbEmpPhotoListRq createKtbEmpPhotoListRq() {
        return new KtbEmpPhotoListRq();
    }

    /**
     * Create an instance of {@link KtbEmpPhotoList }
     * 
     */
    public KtbEmpPhotoList createKtbEmpPhotoList() {
        return new KtbEmpPhotoList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConsent }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetConsent }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetConsent")
    public JAXBElement<GetConsent> createGetConsent(GetConsent value) {
        return new JAXBElement<GetConsent>(_GetConsent_QNAME, GetConsent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConsentResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetConsentResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetConsentResponse")
    public JAXBElement<GetConsentResponse> createGetConsentResponse(GetConsentResponse value) {
        return new JAXBElement<GetConsentResponse>(_GetConsentResponse_QNAME, GetConsentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpByEmail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpByEmail }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetEmpByEmail")
    public JAXBElement<GetEmpByEmail> createGetEmpByEmail(GetEmpByEmail value) {
        return new JAXBElement<GetEmpByEmail>(_GetEmpByEmail_QNAME, GetEmpByEmail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpByEmailResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpByEmailResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetEmpByEmailResponse")
    public JAXBElement<GetEmpByEmailResponse> createGetEmpByEmailResponse(GetEmpByEmailResponse value) {
        return new JAXBElement<GetEmpByEmailResponse>(_GetEmpByEmailResponse_QNAME, GetEmpByEmailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpConsentFlag }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpConsentFlag }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetEmpConsentFlag")
    public JAXBElement<GetEmpConsentFlag> createGetEmpConsentFlag(GetEmpConsentFlag value) {
        return new JAXBElement<GetEmpConsentFlag>(_GetEmpConsentFlag_QNAME, GetEmpConsentFlag.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpConsentFlagResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpConsentFlagResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetEmpConsentFlagResponse")
    public JAXBElement<GetEmpConsentFlagResponse> createGetEmpConsentFlagResponse(GetEmpConsentFlagResponse value) {
        return new JAXBElement<GetEmpConsentFlagResponse>(_GetEmpConsentFlagResponse_QNAME, GetEmpConsentFlagResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPolicyAll }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPolicyAll }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetPolicyAll")
    public JAXBElement<GetPolicyAll> createGetPolicyAll(GetPolicyAll value) {
        return new JAXBElement<GetPolicyAll>(_GetPolicyAll_QNAME, GetPolicyAll.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPolicyAllResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPolicyAllResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "GetPolicyAllResponse")
    public JAXBElement<GetPolicyAllResponse> createGetPolicyAllResponse(GetPolicyAllResponse value) {
        return new JAXBElement<GetPolicyAllResponse>(_GetPolicyAllResponse_QNAME, GetPolicyAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertConsent }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InsertConsent }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "InsertConsent")
    public JAXBElement<InsertConsent> createInsertConsent(InsertConsent value) {
        return new JAXBElement<InsertConsent>(_InsertConsent_QNAME, InsertConsent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertConsentResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InsertConsentResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "InsertConsentResponse")
    public JAXBElement<InsertConsentResponse> createInsertConsentResponse(InsertConsentResponse value) {
        return new JAXBElement<InsertConsentResponse>(_InsertConsentResponse_QNAME, InsertConsentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpAbsence }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpAbsence }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpAbsence")
    public JAXBElement<GetEmpAbsence> createGetEmpAbsence(GetEmpAbsence value) {
        return new JAXBElement<GetEmpAbsence>(_GetEmpAbsence_QNAME, GetEmpAbsence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpAbsenceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpAbsenceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpAbsenceResponse")
    public JAXBElement<GetEmpAbsenceResponse> createGetEmpAbsenceResponse(GetEmpAbsenceResponse value) {
        return new JAXBElement<GetEmpAbsenceResponse>(_GetEmpAbsenceResponse_QNAME, GetEmpAbsenceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpBusinessCard }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpBusinessCard }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpBusinessCard")
    public JAXBElement<GetEmpBusinessCard> createGetEmpBusinessCard(GetEmpBusinessCard value) {
        return new JAXBElement<GetEmpBusinessCard>(_GetEmpBusinessCard_QNAME, GetEmpBusinessCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpBusinessCardResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpBusinessCardResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpBusinessCardResponse")
    public JAXBElement<GetEmpBusinessCardResponse> createGetEmpBusinessCardResponse(GetEmpBusinessCardResponse value) {
        return new JAXBElement<GetEmpBusinessCardResponse>(_GetEmpBusinessCardResponse_QNAME, GetEmpBusinessCardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpContact }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpContact }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpContact")
    public JAXBElement<GetEmpContact> createGetEmpContact(GetEmpContact value) {
        return new JAXBElement<GetEmpContact>(_GetEmpContact_QNAME, GetEmpContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpContactResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpContactResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpContactResponse")
    public JAXBElement<GetEmpContactResponse> createGetEmpContactResponse(GetEmpContactResponse value) {
        return new JAXBElement<GetEmpContactResponse>(_GetEmpContactResponse_QNAME, GetEmpContactResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpName }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpName }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpName")
    public JAXBElement<GetEmpName> createGetEmpName(GetEmpName value) {
        return new JAXBElement<GetEmpName>(_GetEmpName_QNAME, GetEmpName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpNameResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpNameResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpNameResponse")
    public JAXBElement<GetEmpNameResponse> createGetEmpNameResponse(GetEmpNameResponse value) {
        return new JAXBElement<GetEmpNameResponse>(_GetEmpNameResponse_QNAME, GetEmpNameResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpPhoto }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpPhoto }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpPhoto")
    public JAXBElement<GetEmpPhoto> createGetEmpPhoto(GetEmpPhoto value) {
        return new JAXBElement<GetEmpPhoto>(_GetEmpPhoto_QNAME, GetEmpPhoto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoList }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpPhotoList")
    public JAXBElement<GetEmpPhotoList> createGetEmpPhotoList(GetEmpPhotoList value) {
        return new JAXBElement<GetEmpPhotoList>(_GetEmpPhotoList_QNAME, GetEmpPhotoList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoListProc }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoListProc }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpPhotoListProc")
    public JAXBElement<GetEmpPhotoListProc> createGetEmpPhotoListProc(GetEmpPhotoListProc value) {
        return new JAXBElement<GetEmpPhotoListProc>(_GetEmpPhotoListProc_QNAME, GetEmpPhotoListProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoListProcResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoListProcResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpPhotoListProcResponse")
    public JAXBElement<GetEmpPhotoListProcResponse> createGetEmpPhotoListProcResponse(GetEmpPhotoListProcResponse value) {
        return new JAXBElement<GetEmpPhotoListProcResponse>(_GetEmpPhotoListProcResponse_QNAME, GetEmpPhotoListProcResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoListResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoListResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpPhotoListResponse")
    public JAXBElement<GetEmpPhotoListResponse> createGetEmpPhotoListResponse(GetEmpPhotoListResponse value) {
        return new JAXBElement<GetEmpPhotoListResponse>(_GetEmpPhotoListResponse_QNAME, GetEmpPhotoListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpPhotoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpPhotoResponse")
    public JAXBElement<GetEmpPhotoResponse> createGetEmpPhotoResponse(GetEmpPhotoResponse value) {
        return new JAXBElement<GetEmpPhotoResponse>(_GetEmpPhotoResponse_QNAME, GetEmpPhotoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpRC }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpRC }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpRC")
    public JAXBElement<GetEmpRC> createGetEmpRC(GetEmpRC value) {
        return new JAXBElement<GetEmpRC>(_GetEmpRC_QNAME, GetEmpRC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpRCResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpRCResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpRCResponse")
    public JAXBElement<GetEmpRCResponse> createGetEmpRCResponse(GetEmpRCResponse value) {
        return new JAXBElement<GetEmpRCResponse>(_GetEmpRCResponse_QNAME, GetEmpRCResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpSignDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpSignDetail }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpSignDetail")
    public JAXBElement<GetEmpSignDetail> createGetEmpSignDetail(GetEmpSignDetail value) {
        return new JAXBElement<GetEmpSignDetail>(_GetEmpSignDetail_QNAME, GetEmpSignDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmpSignDetailResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmpSignDetailResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmpSignDetailResponse")
    public JAXBElement<GetEmpSignDetailResponse> createGetEmpSignDetailResponse(GetEmpSignDetailResponse value) {
        return new JAXBElement<GetEmpSignDetailResponse>(_GetEmpSignDetailResponse_QNAME, GetEmpSignDetailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployee }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployee }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployee")
    public JAXBElement<GetEmployee> createGetEmployee(GetEmployee value) {
        return new JAXBElement<GetEmployee>(_GetEmployee_QNAME, GetEmployee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeAll }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeAll }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeAll")
    public JAXBElement<GetEmployeeAll> createGetEmployeeAll(GetEmployeeAll value) {
        return new JAXBElement<GetEmployeeAll>(_GetEmployeeAll_QNAME, GetEmployeeAll.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeAllResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeAllResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeAllResponse")
    public JAXBElement<GetEmployeeAllResponse> createGetEmployeeAllResponse(GetEmployeeAllResponse value) {
        return new JAXBElement<GetEmployeeAllResponse>(_GetEmployeeAllResponse_QNAME, GetEmployeeAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByCitizenOrEmplid }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeByCitizenOrEmplid }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeByCitizenOrEmplid")
    public JAXBElement<GetEmployeeByCitizenOrEmplid> createGetEmployeeByCitizenOrEmplid(GetEmployeeByCitizenOrEmplid value) {
        return new JAXBElement<GetEmployeeByCitizenOrEmplid>(_GetEmployeeByCitizenOrEmplid_QNAME, GetEmployeeByCitizenOrEmplid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByCitizenOrEmplidResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeByCitizenOrEmplidResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeByCitizenOrEmplidResponse")
    public JAXBElement<GetEmployeeByCitizenOrEmplidResponse> createGetEmployeeByCitizenOrEmplidResponse(GetEmployeeByCitizenOrEmplidResponse value) {
        return new JAXBElement<GetEmployeeByCitizenOrEmplidResponse>(_GetEmployeeByCitizenOrEmplidResponse_QNAME, GetEmployeeByCitizenOrEmplidResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByName }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeByName }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeByName")
    public JAXBElement<GetEmployeeByName> createGetEmployeeByName(GetEmployeeByName value) {
        return new JAXBElement<GetEmployeeByName>(_GetEmployeeByName_QNAME, GetEmployeeByName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByNameResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeByNameResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeByNameResponse")
    public JAXBElement<GetEmployeeByNameResponse> createGetEmployeeByNameResponse(GetEmployeeByNameResponse value) {
        return new JAXBElement<GetEmployeeByNameResponse>(_GetEmployeeByNameResponse_QNAME, GetEmployeeByNameResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByRankOrCostCenter }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeByRankOrCostCenter }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeByRankOrCostCenter")
    public JAXBElement<GetEmployeeByRankOrCostCenter> createGetEmployeeByRankOrCostCenter(GetEmployeeByRankOrCostCenter value) {
        return new JAXBElement<GetEmployeeByRankOrCostCenter>(_GetEmployeeByRankOrCostCenter_QNAME, GetEmployeeByRankOrCostCenter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByRankOrCostCenterResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeByRankOrCostCenterResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeByRankOrCostCenterResponse")
    public JAXBElement<GetEmployeeByRankOrCostCenterResponse> createGetEmployeeByRankOrCostCenterResponse(GetEmployeeByRankOrCostCenterResponse value) {
        return new JAXBElement<GetEmployeeByRankOrCostCenterResponse>(_GetEmployeeByRankOrCostCenterResponse_QNAME, GetEmployeeByRankOrCostCenterResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeDetail }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeDetail")
    public JAXBElement<GetEmployeeDetail> createGetEmployeeDetail(GetEmployeeDetail value) {
        return new JAXBElement<GetEmployeeDetail>(_GetEmployeeDetail_QNAME, GetEmployeeDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeDetailResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeDetailResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeDetailResponse")
    public JAXBElement<GetEmployeeDetailResponse> createGetEmployeeDetailResponse(GetEmployeeDetailResponse value) {
        return new JAXBElement<GetEmployeeDetailResponse>(_GetEmployeeDetailResponse_QNAME, GetEmployeeDetailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeInfo }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeInfo")
    public JAXBElement<GetEmployeeInfo> createGetEmployeeInfo(GetEmployeeInfo value) {
        return new JAXBElement<GetEmployeeInfo>(_GetEmployeeInfo_QNAME, GetEmployeeInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeInfoResponse")
    public JAXBElement<GetEmployeeInfoResponse> createGetEmployeeInfoResponse(GetEmployeeInfoResponse value) {
        return new JAXBElement<GetEmployeeInfoResponse>(_GetEmployeeInfoResponse_QNAME, GetEmployeeInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getEmployeeResponse")
    public JAXBElement<GetEmployeeResponse> createGetEmployeeResponse(GetEmployeeResponse value) {
        return new JAXBElement<GetEmployeeResponse>(_GetEmployeeResponse_QNAME, GetEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicense }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicense }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicense")
    public JAXBElement<GetLicense> createGetLicense(GetLicense value) {
        return new JAXBElement<GetLicense>(_GetLicense_QNAME, GetLicense.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseInfo }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseInfo")
    public JAXBElement<GetLicenseInfo> createGetLicenseInfo(GetLicenseInfo value) {
        return new JAXBElement<GetLicenseInfo>(_GetLicenseInfo_QNAME, GetLicenseInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseInfoResponse")
    public JAXBElement<GetLicenseInfoResponse> createGetLicenseInfoResponse(GetLicenseInfoResponse value) {
        return new JAXBElement<GetLicenseInfoResponse>(_GetLicenseInfoResponse_QNAME, GetLicenseInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseResponse")
    public JAXBElement<GetLicenseResponse> createGetLicenseResponse(GetLicenseResponse value) {
        return new JAXBElement<GetLicenseResponse>(_GetLicenseResponse_QNAME, GetLicenseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseSub }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseSub }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseSub")
    public JAXBElement<GetLicenseSub> createGetLicenseSub(GetLicenseSub value) {
        return new JAXBElement<GetLicenseSub>(_GetLicenseSub_QNAME, GetLicenseSub.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseSubResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseSubResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseSubResponse")
    public JAXBElement<GetLicenseSubResponse> createGetLicenseSubResponse(GetLicenseSubResponse value) {
        return new JAXBElement<GetLicenseSubResponse>(_GetLicenseSubResponse_QNAME, GetLicenseSubResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseType")
    public JAXBElement<GetLicenseType> createGetLicenseType(GetLicenseType value) {
        return new JAXBElement<GetLicenseType>(_GetLicenseType_QNAME, GetLicenseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLicenseTypeResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLicenseTypeResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getLicenseTypeResponse")
    public JAXBElement<GetLicenseTypeResponse> createGetLicenseTypeResponse(GetLicenseTypeResponse value) {
        return new JAXBElement<GetLicenseTypeResponse>(_GetLicenseTypeResponse_QNAME, GetLicenseTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReportTo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetReportTo }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getReportTo")
    public JAXBElement<GetReportTo> createGetReportTo(GetReportTo value) {
        return new JAXBElement<GetReportTo>(_GetReportTo_QNAME, GetReportTo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReportToResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetReportToResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "getReportToResponse")
    public JAXBElement<GetReportToResponse> createGetReportToResponse(GetReportToResponse value) {
        return new JAXBElement<GetReportToResponse>(_GetReportToResponse_QNAME, GetReportToResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     */
    @XmlElementDecl(namespace = "urn:EmployeeWS/types", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

}
